version: '2'
services:
  itheke-app:
    image: itheke
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://itheke-postgresql:5432/Itheke
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  itheke-postgresql:
    extends:
      file: postgresql.yml
      service: itheke-postgresql
